# wasmer.toml (Versi Lengkap dengan Build Command)

[package]
name = "rakasyailendra/back-end-aksamedia"
version = "0.1.0"
description = "API for Aksamedia Employee Management"

# BAGIAN BARU YANG DITAMBAHKAN
# Memberitahu Wasmer cara membangun aplikasi sebelum dijalankan
[build]
command = "composer install --no-dev --optimize-autoloader"
# ---------------------------------------------

[[module]]
name = "app"
source = "public" # Diarahkan ke folder public
abi = "wasi"

[module.interfaces]
http = { path = "/", port = 8080 } # Menggunakan port yang umum untuk PaaS

[[command]]
name = "start"
module = "app"
runner = "https://webc.org/plumbers/php@8.2"

[command.annotations.wasi]
main-args = [
    "-S", "0.0.0.0:8080",
    "-t", ".", # Root direktori server adalah 'public' yang sudah kita definisikan di atas
]